default_amount: 1000

important_templates:
  patient_reminder:
    amount: 2000

  patient_toolcall2:
    amount: 1500

  patient_toolcall3:
    amount: 1250

random_seed_range:
  min: 1
  max: 999999